---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bluefin-infinitybook-gen10

description: ublue/bluefin for the tuxedo infinitybook pro 14 gen 10

base-image: ghcr.io/ublue-os/bluefin
image-version: latest

modules:
  - type: files
    files:
      - source: system # default, not used atm
        destination: /

  - type: kargs
    arch: x86_64
    kargs:
      - i8042.reset
      - i8042.nomux
      - i8042.nopnp
      - i8042.noloop

  - type: dnf
    repos:
      cleanup: true
      keys:
        - 0x54840598.pub.asc
      files:
        - tuxedo.repo
    install:
      packages:
        - tuxedo-control-center # should include keyboard backlight and function keys
        - tuxedo-yt6801 # ethernet driver, requires disabling secure boot :<

  - type: signing
